# Data Validation - Telco Customer Churn

This notebook checks the dataset before EDA and modeling.

- **Dataset:** IBM Telco Customer Churn
- **Target column:** Churn

## Load Data

In [1]:
import pandas as pd
import numpy as np
import logging
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s"
)
logger = logging.getLogger("data_validation")

df = pd.read_csv(Path("../../data/raw/Telco_Customer_Churn.csv"))
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
logger.info(f"Dataset loaded: {df.shape[0]} rows, {df.shape[1]} columns")
df.head()

2026-06-17 00:51:14,400 | INFO | Dataset loaded: 7043 rows, 21 columns

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

## 1. Dataset Shape Validation

In [2]:
EXPECTED_ROWS = 7043
EXPECTED_COLS = 21

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

assert df.shape[0] == EXPECTED_ROWS, f"Expected {EXPECTED_ROWS} rows but got {df.shape[0]}"
assert df.shape[1] == EXPECTED_COLS, f"Expected {EXPECTED_COLS} columns but got {df.shape[1]}"

logger.info(f"Shape check passed: {df.shape[0]} rows, {df.shape[1]} columns")

2026-06-17 00:51:14,467 | INFO | Shape check passed: 7043 rows, 21 columns

Rows: 7043
Columns: 21

**Note:** We have data to analyze. Empty file would be a problem.

## 2. Schema Validation

In [3]:
EXPECTED_COLUMNS = [
    "customerID", "gender", "SeniorCitizen", "Partner", "Dependents",
    "tenure", "PhoneService", "MultipleLines", "InternetService",
    "OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport",
    "StreamingTV", "StreamingMovies", "Contract", "PaperlessBilling",
    "PaymentMethod", "MonthlyCharges", "TotalCharges", "Churn"
]

print(df.columns.tolist())
print("\nNumber of columns:", len(df.columns))

missing = set(EXPECTED_COLUMNS) - set(df.columns)
extra = set(df.columns) - set(EXPECTED_COLUMNS)

assert len(missing) == 0, f"Missing columns: {missing}"
assert len(extra) == 0, f"Unexpected extra columns: {extra}"

logger.info("Schema check passed: all 21 expected columns present with correct names")

2026-06-17 00:51:14,483 | INFO | Schema check passed: all 21 expected columns present with correct names

['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

Number of columns: 21

**Note:** Churn column must be there because it is our target.

## 3. Data Type Validation

In [4]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [6]:
print("TotalCharges type:", df["TotalCharges"].dtype)
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

TotalCharges type: float64

In [7]:
assert set(df["SeniorCitizen"].unique()).issubset({0, 1}), "Unexpected values in SeniorCitizen"
print("SeniorCitizen unique values:", df["SeniorCitizen"].unique())
print("Note: SeniorCitizen uses 0/1 encoding. All other binary columns use Yes/No strings.")
print("Handle this column separately during feature engineering.")

SeniorCitizen unique values: [0 1]
Note: SeniorCitizen uses 0/1 encoding. All other binary columns use Yes/No strings.
Handle this column separately during feature engineering.

**Note:** TotalCharges should be converted to number in data cleaning step.

## 4. Missing Value Validation

In [8]:
for col in df.select_dtypes(include="object").columns:
    blank_count = (df[col].astype(str).str.strip() == "").sum()
    if blank_count > 0:
        logger.warning(f"{col} has {blank_count} blank/whitespace values")

null_counts = df.isnull().sum()
null_counts = null_counts[null_counts > 0]
if len(null_counts) > 0:
    logger.warning(f"Null values found:\n{null_counts}")
else:
    logger.info("Null check passed: no NaN values found")

print("\nNull check (NaN only):")
print(df.isnull().sum()[df.isnull().sum() > 0])

2026-06-17 00:51:14,733 | WARNING | Null values found:
TotalCharges    11
dtype: int64

Null check (NaN only):
TotalCharges    11
dtype: int64

In [9]:
(df.isnull().sum() / len(df) * 100).round(2)

customerID          0.00
gender              0.00
SeniorCitizen       0.00
Partner             0.00
Dependents          0.00
tenure              0.00
PhoneService        0.00
MultipleLines       0.00
InternetService     0.00
OnlineSecurity      0.00
OnlineBackup        0.00
DeviceProtection    0.00
TechSupport         0.00
StreamingTV         0.00
StreamingMovies     0.00
Contract            0.00
PaperlessBilling    0.00
PaymentMethod       0.00
MonthlyCharges      0.00
TotalCharges        0.16
Churn               0.00
dtype: float64

In [10]:
blank_total = (df["TotalCharges"].astype(str).str.strip() == "").sum()
print("Blank TotalCharges:", blank_total)
print("Missing after numeric conversion:", df["TotalCharges"].isnull().sum())

Blank TotalCharges: 0
Missing after numeric conversion: 11

**Note:** Some new customers have blank TotalCharges when tenure is 0.

## 5. Duplicate Record Validation

In [11]:
assert df.duplicated().sum() == 0, "Duplicate rows found"
assert df["customerID"].duplicated().sum() == 0, "Duplicate customerID found"
logger.info("Duplicate check passed: no duplicate rows or customerIDs")

2026-06-17 00:51:14,859 | INFO | Duplicate check passed: no duplicate rows or customerIDs

**Note:** No duplicates is good - each row is one customer.

## 6. Unique Value Analysis

In [12]:
df.nunique()

customerID          7043
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6530
Churn                  2
dtype: int64

In [13]:
print("Unique customerID:", df["customerID"].nunique())
print("Total rows:", len(df))

Unique customerID: 7043
Total rows: 7043

**Note:** customerID is unique for each row. Other columns like gender have only 2 values.

## 7. Numerical Data Validation

In [14]:
df[["SeniorCitizen", "tenure", "MonthlyCharges", "TotalCharges"]].describe()

       SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    7043.000000  7043.000000     7043.000000   7032.000000
mean        0.162147    32.371149       64.761692   2283.300441
std         0.368612    24.559481       30.090047   2266.771362
min         0.000000     0.000000       18.250000     18.800000
25%         0.000000     9.000000       35.500000    401.450000
50%         0.000000    29.000000       70.350000   1397.475000
75%         0.000000    55.000000       89.850000   3794.737500
max         1.000000    72.000000      118.750000   8684.800000

In [15]:
assert (df["tenure"] < 0).sum() == 0, "Negative tenure values found"
assert (df["MonthlyCharges"] < 0).sum() == 0, "Negative MonthlyCharges values found"
assert (df["TotalCharges"] < 0).sum() == 0, "Negative TotalCharges values found"

print("Negative tenure: 0")
print("Negative MonthlyCharges: 0")
print("Negative TotalCharges: 0")

for col in ["tenure", "MonthlyCharges", "TotalCharges"]:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    print(f"{col} outliers: {len(outliers)}")

Negative tenure: 0
Negative MonthlyCharges: 0
Negative TotalCharges: 0
tenure outliers: 0
MonthlyCharges outliers: 0
TotalCharges outliers: 0

**Note:** Values look reasonable. Tenure is between 0 and 72 months.

## 8. Categorical Data Validation

In [16]:
expected_categories = {
    "gender": {"Female", "Male"},
    "Partner": {"Yes", "No"},
    "Dependents": {"Yes", "No"},
    "PhoneService": {"Yes", "No"},
    "MultipleLines": {"No phone service", "No", "Yes"},
    "InternetService": {"DSL", "Fiber optic", "No"},
    "OnlineSecurity": {"No", "Yes", "No internet service"},
    "OnlineBackup": {"Yes", "No", "No internet service"},
    "DeviceProtection": {"No", "Yes", "No internet service"},
    "TechSupport": {"No", "Yes", "No internet service"},
    "StreamingTV": {"No", "Yes", "No internet service"},
    "StreamingMovies": {"No", "Yes", "No internet service"},
    "Contract": {"Month-to-month", "One year", "Two year"},
    "PaperlessBilling": {"Yes", "No"},
    "PaymentMethod": {
        "Electronic check",
        "Mailed check",
        "Bank transfer (automatic)",
        "Credit card (automatic)",
    },
    "Churn": {"No", "Yes"},
}

for col, expected in expected_categories.items():
    actual = set(df[col].unique())
    assert actual.issubset(expected), f"Unexpected values in {col}: {actual - expected}"
    print(f"{col}: {df[col].unique()}")

gender: ['Female' 'Male']
Partner: ['Yes' 'No']
Dependents: ['No' 'Yes']
PhoneService: ['No' 'Yes']
MultipleLines: ['No phone service' 'No' 'Yes']
InternetService: ['DSL' 'Fiber optic' 'No']
OnlineSecurity: ['No' 'Yes' 'No internet service']
OnlineBackup: ['Yes' 'No' 'No internet service']
DeviceProtection: ['No' 'Yes' 'No internet service']
TechSupport: ['No' 'Yes' 'No internet service']
StreamingTV: ['No' 'Yes' 'No internet service']
StreamingMovies: ['No' 'Yes' 'No internet service']
Contract: ['Month-to-month' 'One year' 'Two year']
PaperlessBilling: ['Yes' 'No']
PaymentMethod: ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
Churn: ['No' 'Yes']

**Note:** Categories look normal - Yes/No, contract types, payment methods etc.

## 9. Target Variable Validation

In [17]:
df["Churn"].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [18]:
churn_rate = (df["Churn"] == "Yes").mean() * 100
print("Churn %:", round(churn_rate, 2))

Churn %: 26.54

**Note:** About 27% churn. More customers stay than leave (imbalanced data).

## 10. Data Leakage Check

In [19]:
forbidden_cols = ["customerID", "Churn"]
features = [col for col in df.columns if col not in forbidden_cols]

for col in forbidden_cols:
    assert col not in features, f"Data leakage error: {col} is in the features list!"

logger.info(f"Leakage check passed: {len(features)} features selected, ID and Target excluded")

2026-06-17 00:51:15,172 | INFO | Leakage check passed: 19 features selected, ID and Target excluded

In [20]:
corr_tenure = df["TotalCharges"].corr(df["tenure"])
corr_monthly = df["TotalCharges"].corr(df["MonthlyCharges"])

print(f"Correlation between TotalCharges and tenure: {round(corr_tenure, 4)}")
print(f"Correlation between TotalCharges and MonthlyCharges: {round(corr_monthly, 4)}")

if corr_tenure > 0.8 or corr_monthly > 0.8:
    logger.warning("TotalCharges is highly correlated with another feature. Consider dropping it during feature engineering.")
else:
    logger.info("TotalCharges multicollinearity check passed.")

2026-06-17 00:51:15,203 | WARNING | TotalCharges is highly correlated with another feature. Consider dropping it during feature engineering.

Correlation between TotalCharges and tenure: 0.8259
Correlation between TotalCharges and MonthlyCharges: 0.6511

**Note:** Using target as feature would cheat the model. ID has no meaning for prediction.

## 11. Business Rule Validation

In [21]:
print("Tenure = 0 customers:", (df["tenure"] == 0).sum())

tenure_zero = df[df["tenure"] == 0]
blank = (tenure_zero["TotalCharges"].astype(str).str.strip() == "").sum()
print("Blank TotalCharges when tenure is 0:", blank)

Tenure = 0 customers: 11
Blank TotalCharges when tenure is 0: 0

In [22]:
mask = (df["tenure"] >= 1) & df["TotalCharges"].notna()
issue = df[mask & (df["TotalCharges"] < df["MonthlyCharges"])]
assert len(issue) == 0, f"Business rule violation: {len(issue)} customers have TotalCharges < MonthlyCharges"
logger.info("Business rule check passed: no TotalCharges < MonthlyCharges violations")

2026-06-17 00:51:15,257 | INFO | Business rule check passed: no TotalCharges < MonthlyCharges violations

In [23]:
internet_cols = ["OnlineSecurity", "OnlineBackup", "DeviceProtection",
                 "TechSupport", "StreamingTV", "StreamingMovies"]

for col in internet_cols:
    violations = df[(df["InternetService"] == "No") & (df[col] != "No internet service")]
    assert len(violations) == 0, f"{col} has {len(violations)} rows inconsistent with InternetService=No"

phone_violations = df[(df["PhoneService"] == "No") & (df["MultipleLines"] != "No phone service")]
assert len(phone_violations) == 0, f"MultipleLines has {len(phone_violations)} rows inconsistent with PhoneService=No"

logger.info("Cross-column consistency check passed!")

2026-06-17 00:51:15,308 | INFO | Cross-column consistency check passed!

**Note:** New customers (tenure 0) may not have total charges yet. That is normal.

## 12. Validation Summary

In [24]:
missing_total_charges = df["TotalCharges"].isnull().sum()
churn_rate = round((df["Churn"] == "Yes").mean() * 100, 2)
duplicate_rows = df.duplicated().sum()

print("SUMMARY")
print("--------")
print(f"Rows: {df.shape[0]} | Columns: {df.shape[1]}")
print(f"Duplicates: {duplicate_rows}")
print(f"Issue: {missing_total_charges} missing TotalCharges (tenure 0)")
print(f"Churn rate: {churn_rate}%")
print()
print("Before EDA:")
print("1. Fix TotalCharges datatype")
print("2. Handle missing TotalCharges")
print("3. Remove customerID from features")
print("4. Start EDA notebook")

logger.info("Data validation completed successfully.")

2026-06-17 00:51:15,352 | INFO | Data validation completed successfully.

SUMMARY
--------
Rows: 7043 | Columns: 21
Duplicates: 0
Issue: 11 missing TotalCharges (tenure 0)
Churn rate: 26.54%

Before EDA:
1. Fix TotalCharges datatype
2. Handle missing TotalCharges
3. Remove customerID from features
4. Start EDA notebook